<?php

$GLOBALS["trans"] = [
	//login/main page
	"welcome" => "WELCOME TO OUR SITE",
	"title" => "Welcome | Registration & Login Form",
	"signin" => "Sign In",
	"email" => "Email",
	"password" => "Password",
	"remember" => "Remember Me",
	"login" => "LOGIN",
	"notreg" => "Not registered?",
	"signup" => "Sign Up",

	//registration page
	"req_field" => "Required fields",
	"name" => "Name",
	"surname" => "Surname",
	"midname" => "Middle Name",
	"rep_pass" => "Repeat Password",
	"pass_desc" => "requires digits, uppercase and lowercase letters, <br/>at least 8 characters",
	"dateofbirth" => "Date of Birth",
	"selectdatebirth" => "Select a date of birth",
	"month" => "Month",
	"day" => "Day",
	"year" => "Year",
	"city" => "City",
	"mobnum" => "Mobile Number",
	"phonenum" => "Phone Number",
	"onlydig" => "Only Digits",
	"gender" => "Gender",
	"male" => "Male",
	"female" => "Female",
	"education" => "Education",
	"work" => "Work Experience",
	"additional" => "Additional information about yourself",
	"upload" => "Upload Photo",
	"submit" => "SUBMIT",

	//errors / rules
	"name_err" => "should be 2 - 50 length,<br/>only Latin letters, dashes and quotes",
	"pass_err" => "Password should be at least 8 characters<br/>digits, uppercase and lowercase letters",
	"rep_pass_err" => "Password doesn't match the confirm password",
	"mail_err" => "Invalid email",
	"city_err" => "Invalid city name",
	"mob_err" => "Mobile number requires only digits, at least 6",
	"phone_err" => "Phone number requires only digits, at least 6",
	"textar_err" => "Field shouldn't exceed 1000 characters",
	"photo_err" => "Only jpeg, png and gif extensions supported. <br>File max size - 2MB",

	"nouser" => "User is not found",
	"fillinreq" => "Fill in required fields",
	"invalid" => "Invalid",
	"incpass" => "Incorrect Password",
	"mailtaken" => "Email is already taken",
	"selectgender" => "Select gender",
	"day_err" => "Select the day of birth",
	"year_err" => "Select the year of birth",
	"month_err" => "Select the month of birth",
	"area_err" => "area should not exceed 1000 characters",
	"max_size" => "File size should be less then 2MB",
	"img_ext_err" => "File should be an image(jpeg, png, gif)",
	"upl_fail" => "File uploading failed",
	"reg_suc" => "You have been succsessfully registered!",
	"userinfo" => "User Info",
	"logout" => "Logout",

	//months
	"jan" => "January",
	"feb" => "February",
	"mar" => "March",
	"apr" => "April",
	"may" => "May",
	"jun" => "June",
	"jul" => "July",
	"aug" => "August",
	"sep" => "September",
	"oct" => "October",
	"nov" => "November",
	"dec" => "December",

];
